<x-layouts.app title="Обзор — CEO Stat">
    <style>
        @keyframes metric-number-wiggle {
            0% { transform: translate3d(0, 0, 0) scale(1); }
            35% { transform: translate3d(3px, -4px, 0) scale(1.045); }
            65% { transform: translate3d(-2px, -1px, 0) scale(1.025); }
            100% { transform: translate3d(0, 0, 0) scale(1); }
        }
        .number-hover-card > p:last-child { transform-origin: left center; }
        .number-hover-card:hover > p:last-child { animation: metric-number-wiggle 420ms ease-out; }
        @media (prefers-reduced-motion: reduce) { .number-hover-card:hover > p:last-child { animation: none; } }
    </style>
    <div class="mx-auto min-h-screen max-w-7xl px-3 py-4 sm:px-6 sm:py-5 lg:px-8">
        <header class="mb-4 sm:mb-7"><h1 class="text-xl font-extrabold sm:text-2xl">Результаты торговли</h1></header>
        <div class="mb-3 flex items-center justify-between rounded-xl bg-white p-1.5 sm:hidden"><button type="button" data-dashboard-month-change="-1" class="grid size-9 place-items-center rounded-lg font-extrabold text-[#605bff]" aria-label="Предыдущий месяц">←</button><strong class="capitalize" data-dashboard-period-name>{{ $monthLabel }}</strong><button type="button" data-dashboard-month-change="1" class="grid size-9 place-items-center rounded-lg font-extrabold text-[#605bff]" aria-label="Следующий месяц">→</button></div>
        <section class="mobile-summary-list mb-5 space-y-3 sm:hidden">
            <details class="group overflow-hidden rounded-xl bg-[#605bff] text-white"><summary class="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><div><p class="text-[10px] font-bold uppercase tracking-wider text-white/60">Итого за всё время</p><p class="mt-1 text-2xl font-extrabold">{{ number_format($allTimeProfit, 2, ',', ' ') }}</p></div><span class="text-xl transition group-open:rotate-180">⌄</span></summary><div class="grid grid-cols-3 gap-2 border-t border-white/10 px-4 py-3 text-center"><div><p class="text-[9px] text-white/55">Доходность</p><strong class="text-xs">{{ number_format($allTimePercent, 3, ',', ' ') }}%</strong></div><div><p class="text-[9px] text-white/55">% в день</p><strong class="text-xs">{{ number_format($allTimeDayPercent, 3, ',', ' ') }}%</strong></div><div><p class="text-[9px] text-white/55">Среднее</p><strong class="text-xs">{{ number_format($allTimeDailyAverage, 2, ',', ' ') }}</strong></div></div></details>
            <details class="group overflow-hidden rounded-xl bg-[#030229] text-white"><summary class="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><div><p class="text-[10px] font-bold uppercase tracking-wider text-white/60" data-dashboard-month-label>Итого за {{ $monthLabel }}</p><p class="mt-1 text-2xl font-extrabold" data-dashboard-stat="month-profit">{{ number_format($monthProfit, 2, ',', ' ') }}</p></div><span class="text-xl transition group-open:rotate-180">⌄</span></summary><div class="grid grid-cols-3 gap-2 border-t border-white/10 px-4 py-3 text-center"><div><p class="text-[9px] text-white/55">Доходность</p><strong class="text-xs" data-dashboard-stat="month-percent">{{ number_format($monthPercent, 3, ',', ' ') }}%</strong></div><div><p class="text-[9px] text-white/55">% в день</p><strong class="text-xs" data-dashboard-stat="day-percent">{{ number_format($dayPercent, 3, ',', ' ') }}%</strong></div><div><p class="text-[9px] text-white/55">Среднее</p><strong class="text-xs" data-dashboard-stat="daily-average">{{ number_format($dailyAverage, 2, ',', ' ') }}</strong></div></div></details>
            <details class="group overflow-hidden rounded-xl bg-white"><summary class="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><div><p class="text-[10px] font-bold uppercase tracking-wider text-[#030229]/45">Итого за сегодня</p><p class="mt-1 text-2xl font-extrabold {{ $todayProfit < 0 ? 'text-red-700' : 'text-[#605bff]' }}">{{ number_format($todayProfit, 2, ',', ' ') }}</p></div><span class="text-xl text-[#605bff] transition group-open:rotate-180">⌄</span></summary><div class="grid grid-cols-3 gap-2 border-t border-[#030229]/5 px-4 py-3 text-center"><div><p class="text-[9px] text-[#030229]/40">Доходность</p><strong class="text-xs">{{ number_format($todayPercent, 3, ',', ' ') }}%</strong></div><div><p class="text-[9px] text-[#030229]/40">Операций</p><strong class="text-xs">{{ $todayOperations }}</strong></div><div><p class="text-[9px] text-[#030229]/40">Среднее</p><strong class="text-xs">{{ number_format($todayAverage, 2, ',', ' ') }}</strong></div></div></details>
        </section>
        <section class="mb-4 hidden gap-4 sm:grid sm:grid-cols-2 xl:grid-cols-4">
            <article class="number-hover-card min-w-[78vw] snap-start rounded-[10px] bg-[#605bff] p-5 text-white sm:min-w-0"><p class="text-xs font-bold uppercase tracking-wider text-white/65">Итого за всё время</p><p class="mt-2 text-3xl font-extrabold">{{ number_format($allTimeProfit, 2, ',', ' ') }}</p></article>
            <article class="stat-card number-hover-card min-w-[78vw] snap-start sm:min-w-0"><p class="stat-label">% за всё время</p><p class="stat-value {{ $allTimePercent >= 0 ? 'text-[#605bff]' : 'text-red-700' }}">{{ number_format($allTimePercent, 3, ',', ' ') }}%</p></article>
            <article class="stat-card number-hover-card min-w-[78vw] snap-start sm:min-w-0"><p class="stat-label">% в день за всё время</p><p class="stat-value {{ $allTimeDayPercent >= 0 ? 'text-[#605bff]' : 'text-red-700' }}">{{ number_format($allTimeDayPercent, 3, ',', ' ') }}%</p></article>
            <article class="stat-card number-hover-card min-w-[78vw] snap-start sm:min-w-0"><p class="stat-label">Среднее в день за всё время</p><p class="stat-value">{{ number_format($allTimeDailyAverage, 2, ',', ' ') }}</p></article>
        </section>
        <section class="mb-7 hidden gap-4 sm:grid sm:grid-cols-2 xl:grid-cols-4">
            <article class="number-hover-card min-w-[78vw] snap-start rounded-[10px] bg-[#030229] p-5 text-white sm:min-w-0"><p class="text-xs font-bold uppercase tracking-wider text-white/60" data-dashboard-month-label>Итого за {{ $monthLabel }}</p><p class="mt-2 text-3xl font-extrabold" data-dashboard-stat="month-profit">{{ number_format($monthProfit, 2, ',', ' ') }}</p></article>
            <article class="stat-card number-hover-card min-w-[78vw] snap-start sm:min-w-0"><p class="stat-label">% за месяц</p><p class="stat-value {{ $monthPercent >= 0 ? 'text-[#605bff]' : 'text-red-700' }}" data-dashboard-stat="month-percent">{{ number_format($monthPercent, 3, ',', ' ') }}%</p></article>
            <article class="stat-card number-hover-card min-w-[78vw] snap-start sm:min-w-0"><p class="stat-label">% за день</p><p class="stat-value {{ $dayPercent >= 0 ? 'text-[#605bff]' : 'text-red-700' }}" data-dashboard-stat="day-percent">{{ number_format($dayPercent, 3, ',', ' ') }}%</p></article>
            <article class="stat-card number-hover-card min-w-[78vw] snap-start sm:min-w-0"><p class="stat-label">Среднее в день</p><p class="stat-value" data-dashboard-stat="daily-average">{{ number_format($dailyAverage, 2, ',', ' ') }}</p></article>
        </section>
        <section class="mb-7 hidden gap-5 sm:grid sm:grid-cols-2 xl:grid-cols-4">
            <article class="relative h-[200px] min-w-[84vw] snap-start overflow-hidden rounded-[10px] bg-white p-4 sm:h-[220px] sm:min-w-0 sm:p-5">
                <div class="relative z-10 flex items-center justify-between gap-3"><div class="flex items-center gap-3"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#5b93ff]/10 text-xl text-[#5b93ff]">↗</span><div><p class="text-sm text-[#030229]/55">Динамика по дням</p><p class="mt-0.5 text-2xl font-extrabold" data-dashboard-stat="month-profit">{{ number_format($monthProfit, 2, ',', ' ') }}</p></div></div><span class="text-right text-xs font-bold {{ $monthPercent >= 0 ? 'text-[#605bff]' : 'text-red-600' }}" data-dashboard-stat="month-percent-signed">{{ $monthPercent >= 0 ? '+' : '' }}{{ number_format($monthPercent, 3, ',', ' ') }}% за месяц</span></div>
                <div class="absolute inset-x-0 bottom-0 h-[105px]"><canvas id="daily-results-chart"></canvas></div>
            </article>
            <article class="relative h-[200px] min-w-[84vw] snap-start overflow-hidden rounded-[10px] bg-white p-4 sm:h-[220px] sm:min-w-0 sm:p-5">
                <div class="relative z-10 flex items-center justify-between gap-3"><div class="flex items-center gap-3"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#ffd66b]/20 text-xl text-[#c28a00]">∑</span><div><p class="text-sm text-[#030229]/55">Накопительный результат</p><p class="mt-0.5 text-2xl font-extrabold">{{ number_format($allTimeProfit, 2, ',', ' ') }}</p></div></div><span class="text-right text-xs font-bold {{ $allTimePercent >= 0 ? 'text-[#605bff]' : 'text-red-600' }}">{{ $allTimePercent >= 0 ? '+' : '' }}{{ number_format($allTimePercent, 3, ',', ' ') }}% за всё время</span></div>
                <div class="absolute inset-x-0 bottom-0 h-[105px]"><canvas id="cumulative-results-chart"></canvas></div>
            </article>
            <article class="relative h-[200px] min-w-[84vw] snap-start overflow-hidden rounded-[10px] bg-white p-4 sm:h-[220px] sm:min-w-0 sm:p-5">
                <div class="relative z-10 flex items-center justify-between gap-3"><div class="flex items-center gap-3"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#ff8f6b]/10 text-xl text-[#ff8f6b]">▥</span><div><p class="text-sm text-[#030229]/55">Результаты по месяцам</p><p class="mt-0.5 text-2xl font-extrabold">{{ number_format($allTimeProfit, 2, ',', ' ') }}</p></div></div><span class="text-right text-xs font-bold text-[#ff8f6b]">{{ count($chartData['monthly']['labels']) }} мес. с данными</span></div>
                <div class="absolute inset-x-0 bottom-0 h-[105px]"><canvas id="monthly-results-chart"></canvas></div>
            </article>
            <article class="relative h-[200px] min-w-[84vw] snap-start overflow-hidden rounded-[10px] bg-white p-4 sm:h-[220px] sm:min-w-0 sm:p-5">
                <div class="relative z-10 flex items-center justify-between gap-3"><div class="flex items-center gap-3"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#605bff]/10 text-xl text-[#605bff]">◎</span><div><p class="text-sm text-[#030229]/55">Сравнение роботов</p><p class="mt-0.5 text-2xl font-extrabold">{{ $robotsCount }}</p></div></div><span class="text-right text-xs font-bold text-[#605bff]">Активных роботов</span></div>
                <div class="absolute inset-x-0 bottom-0 h-[105px]"><canvas id="robot-results-chart"></canvas></div>
            </article>
        </section>
        <script id="dashboard-chart-data" type="application/json" data-month="{{ $month }}">@json($chartData)</script>
        <details class="group mb-5 overflow-hidden rounded-xl bg-white sm:hidden"><summary class="flex cursor-pointer list-none items-center justify-between p-4"><div><p class="text-[10px] font-extrabold uppercase tracking-wider text-[#030229]/40">История</p><h2 class="mt-1 font-extrabold">Последние записи</h2></div><span class="text-xl text-[#605bff] transition group-open:rotate-180">⌄</span></summary><div class="max-h-96 space-y-2 overflow-y-auto border-t border-[#030229]/5 p-3">@forelse($recentResults as $result)<div class="flex items-center justify-between rounded-lg bg-[#fafafb] p-3"><div><p class="text-sm font-bold">{{ $result->account->robot->name }}</p><p class="text-xs text-[#030229]/40">{{ $result->traded_at->format('d.m.Y') }}</p></div><span class="font-extrabold {{ $result->amount >= 0 ? 'text-[#605bff]' : 'text-red-700' }}">{{ $result->amount >= 0 ? '+' : '' }}{{ number_format($result->amount, 2, ',', ' ') }}</span></div>@empty<p class="p-3 text-sm text-stone-500">Записей пока нет.</p>@endforelse</div></details>
        <section class="hidden gap-6 sm:grid lg:grid-cols-[1fr_340px]">
            <livewire:result-calendar :read-only="true" />
            <div class="relative min-h-96 lg:min-h-0" style="align-self: stretch;">
                <aside class="flex h-full min-h-0 flex-col overflow-hidden rounded-[10px] bg-white p-5 lg:absolute lg:inset-0">
                    <div class="mb-4 shrink-0"><p class="text-[10px] font-extrabold uppercase tracking-wider text-[#030229]/40">История</p><h2 class="mt-1 font-extrabold">Последние записи</h2><p class="mt-1 text-xs text-[#030229]/40">До 100 последних операций</p></div>
                    <div class="min-h-0 flex-1 space-y-3 overflow-y-auto pr-2">@forelse($recentResults as $result)<div class="flex items-center justify-between rounded-lg bg-[#fafafb] p-3"><div><p class="text-sm font-bold">{{ $result->account->robot->name }}</p><p class="text-xs text-[#030229]/40">{{ $result->traded_at->format('d.m.Y') }}</p></div><span class="font-extrabold {{ $result->amount >= 0 ? 'text-[#605bff]' : 'text-red-700' }}">{{ $result->amount >= 0 ? '+' : '' }}{{ number_format($result->amount, 2, ',', ' ') }}</span></div>@empty<p class="rounded-xl bg-stone-50 p-4 text-sm text-stone-500">Записей пока нет.</p>@endforelse</div>
                </aside>
            </div>
        </section>
    </div>
</x-layouts.app>
