<main class="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8">
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><a href="{{ route('robots.index') }}" class="text-sm font-bold text-green-900">← Все роботы</a><h1 class="mt-2 text-2xl font-extrabold">{{ $robot->name }}</h1><p class="mt-1 text-sm text-stone-500">{{ $robot->description ?: 'Учет показателей торгового робота' }}</p></div><span class="rounded-full px-3 py-1.5 text-xs font-bold {{ $robot->is_active ? 'bg-green-100 text-green-900' : 'bg-stone-200 text-stone-600' }}">{{ $robot->is_active ? 'Активен' : 'Отключён' }}</span></div>
    <section class="mb-6 grid gap-4 sm:grid-cols-3"><article class="rounded-2xl bg-green-950 p-5 text-white"><p class="stat-label text-white/60">Результат за месяц</p><p class="stat-value">{{ number_format($monthProfit, 2, ',', ' ') }}</p></article><article class="stat-card"><p class="stat-label">Торговых дней</p><p class="stat-value">{{ $activeDays }}</p></article><article class="stat-card"><p class="stat-label">Текущий баланс</p><p class="stat-value">{{ number_format((float)($robot->account?->current_balance ?? 0), 2, ',', ' ') }}</p></article></section>
    <div class="grid gap-6 xl:grid-cols-[1fr_340px]">
        <livewire:result-calendar :robot-id="$robot->id" :key="'calendar-'.$robot->id" />
        @if(in_array(auth()->user()->role->value, ['admin', 'operator'], true))<form wire:submit="saveAccount" class="h-fit rounded-2xl border border-stone-200 bg-white p-5"><h2 class="mb-4 font-extrabold">Торговый счёт</h2>@if(session('account-status'))<p class="mb-4 rounded-xl bg-green-100 p-3 text-sm font-bold text-green-900">{{ session('account-status') }}</p>@endif
            <div class="space-y-4"><div><label class="form-label">Название</label><input wire:model="name" class="form-input" placeholder="Основной счёт">@error('name')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div><div><label class="form-label">Брокер</label><input wire:model="broker" class="form-input"></div><div class="grid grid-cols-2 gap-3"><div><label class="form-label">Платформа</label><select wire:model="platform" class="form-input"><option value="manual">Ручной</option><option value="mt4">MT4</option><option value="mt5">MT5</option></select></div><div><label class="form-label">Валюта</label><input wire:model="currency" maxlength="3" class="form-input"></div></div><div><label class="form-label">Логин счёта</label><input wire:model="externalLogin" class="form-input"></div><div class="grid grid-cols-2 gap-3"><div><label class="form-label">Депозит</label><input wire:model="initialDeposit" inputmode="decimal" class="form-input"></div><div><label class="form-label">Баланс</label><input wire:model="currentBalance" inputmode="decimal" class="form-input"></div></div><label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" wire:model="isActive" class="size-4 rounded"> Счёт активен</label></div>
            <button class="btn-primary mt-5 w-full">Сохранить счёт</button>
        </form>@endif
    </div>
</main>
