<main class="mx-auto max-w-7xl px-3 py-5 sm:px-6 sm:py-7 lg:px-8">
    <div class="mb-6"><h1 class="text-2xl font-extrabold">Пользователи</h1><p class="mt-1 text-sm text-stone-500">Роли и доступ наблюдателей к роботам</p></div>
    <div class="grid gap-6 lg:grid-cols-[380px_1fr]">
        <form wire:submit="save" class="h-fit rounded-[10px] bg-white p-5">
            <h2 class="mb-4 font-extrabold">{{ $editingId ? 'Редактировать' : 'Новый пользователь' }}</h2>
            <div class="space-y-4">
                <div><label class="form-label">Имя</label><input wire:model="name" class="form-input">@error('name')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
                <div><label class="form-label">Email</label><input type="email" wire:model="email" class="form-input">@error('email')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
                <div><label class="form-label">Роль</label><select wire:model.live="role" class="form-input"><option value="viewer">Наблюдатель</option><option value="operator">Оператор</option><option value="admin">Администратор</option></select></div>
                <div><label class="form-label">Пароль {{ $editingId ? '(оставьте пустым, чтобы не менять)' : '' }}</label><input type="password" wire:model="password" class="form-input" autocomplete="new-password">@error('password')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
                @if($role === 'viewer')<fieldset><legend class="form-label">Доступные роботы</legend><div class="max-h-48 space-y-2 overflow-y-auto rounded-xl border border-stone-200 p-3">@forelse($robots as $robot)<label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" wire:model="robotIds" value="{{ $robot->id }}" class="size-4 rounded"> {{ $robot->name }}</label>@empty<p class="text-sm text-stone-500">Роботов пока нет.</p>@endforelse</div></fieldset>@endif
                <label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" wire:model="isActive" class="size-4 rounded"> Доступ активен</label>
            </div>
            <div class="mt-5 flex gap-2"><button class="btn-primary">Сохранить</button>@if($editingId)<button type="button" wire:click="cancel" class="btn-secondary">Отмена</button>@endif</div>
        </form>
        <section class="rounded-[10px] bg-white p-4 sm:p-5">
            @if(session('status'))<p class="mb-4 rounded-lg bg-[#605bff]/10 px-4 py-3 text-sm font-bold text-[#605bff]">{{ session('status') }}</p>@endif
            <div class="space-y-3">@foreach($users as $user)<article class="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-[#fafafb] p-4"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><strong>{{ $user->name }}</strong><span class="rounded-lg bg-[#030229]/5 px-2 py-1 text-xs font-bold">{{ $user->role->label() }}</span><span class="rounded-lg px-2 py-1 text-xs font-bold {{ $user->is_active ? 'bg-[#605bff]/10 text-[#605bff]' : 'bg-red-100 text-red-700' }}">{{ $user->is_active ? 'Активен' : 'Отключён' }}</span></div><p class="mt-1 break-all text-sm text-stone-500">{{ $user->email }}</p>@if($user->role === \App\Enums\UserRole::Viewer)<p class="mt-1 text-xs text-stone-500">{{ $user->robots->isEmpty() ? 'Роботы не назначены' : $user->robots->pluck('name')->join(', ') }}</p>@endif</div><div class="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto"><button wire:click="edit({{ $user->id }})" class="btn-secondary">Изменить</button>@if($user->id !== auth()->id())<button wire:click="confirmDelete({{ $user->id }})" class="btn-secondary text-red-700">Удалить</button>@endif</div></article>@endforeach</div>
        </section>
    </div>
    @if($deletingId)<div class="fixed inset-0 z-50 grid place-items-center bg-stone-950/60 p-4"><form wire:submit="delete" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 class="text-xl font-extrabold">Удаление пользователя</h2><p class="mt-2 text-sm text-stone-600">Удалить «{{ $deletingUser?->name }}»? Действие необратимо.</p><div class="mt-5"><label class="form-label">Ваш пароль</label><input type="password" wire:model="deletePassword" class="form-input" autocomplete="current-password" autofocus>@error('deletePassword')<p class="mt-1 text-xs font-bold text-red-700">{{ $message }}</p>@enderror</div><div class="mt-6 flex justify-end gap-2"><button type="button" wire:click="cancelDelete" class="btn-secondary">Отмена</button><button class="rounded-xl bg-red-700 px-4 py-2.5 text-sm font-extrabold text-white">Удалить</button></div></form></div>@endif
</main>
